### ISSUE TITLE
It disables screenshots

### ISSUE THREAD

**Issue by pineda97** [SpazeDog/xposed-additions#10]
When using this module the conventional method for taking a screenshot is disabled. Because after I installed this module the power and volume down method (for taking a screenshot) stopped working. I don't know if this has happened to anyone else, but that's what happened on my device. For the record it's a Huawei g610 u15 with an AOSP rom

**Comment by dbergloev** [comment]
Yes I know about this, not sure why or if it will be fixed in this version or next. For now, just create it manually using remap and the screenshot action.
