### ISSUE TITLE
707aa96 and Android 4.2.2: reflection error

### ISSUE THREAD

**Issue by gerhardol** [SpazeDog/xposed-additions#20]
707aa96 did not handle API 17 (4.2) correctly for goToSleep so there  was an exception at init

Note: the method is not used by the module

See https://github.com/gerhardol/xposed-additions/commit/101c9152e3d07853d2548b3617b4911acfe0af68

**Comment by dbergloev** [comment]
Okay I must have gotten one of the SDK versions mixed up, there is a lot of different versions of that class at this point. 

What do you mean not used by the module? It is used [here](https://github.com/SpazeDog/xposed-additions/blob/3.4.x/src/com/spazedog/xposed/additionsgb/backend/pwm/iface/IEventMediator.java#L264).

**Comment by gerhardol** [comment]
At least in my mod, changeDisplayState() is only called with true as an argument, so goToSleep is not called.

https://github.com/SpazeDog/xposed-additions/blob/3.4.x/src/com/spazedog/xposed/additionsgb/backend/pwm/iface/IEventMediator.java#L649

**Comment by dbergloev** [comment]
I think that you are right, but that is a mistake. Some Stock ROM's does not work properly with the power key while it is being injected, so `changeDisplayState` should always be used to change display state (Every power code) regardless of the current state of the screen.

**Comment by gerhardol** [comment]
It seems like this was manually merged in 3.4.x branch and I assume in the 3.5.0 release. Closing.
