### ISSUE TITLE
Soft Keyboard state tracking

### ISSUE THREAD

**Issue by infernix** [SpazeDog/xposed-additions#25]
I'm trying to disable click functions and change them to double click for all hardware capacitive buttons on my OnePlus One whenever the software keyboard is shown (Swiftkey in my case). Selecting Swiftkey as an app does not seem to work; I can only achieve this by using Screen On state and that's a bit too broad.  I know Tasker can track "Keyboard Out" state but I didn't find a way to go from Tasker to Xposed Additions.

 Is it possible to add a state called "Showing Keyboard" that would work for all software/on-screen keyboards?

(I posted this on the XDA thread but figured this is the better place for it)

**Comment by dbergloev** [comment]
That is not a bad idea. I am currently working on a new version of this
app, I might add this to that version. Sadly the old version is not very
flexible in design, so you will have to wait until the new one is finished
and considering that I have started from scratch, it might take awhile.
